export const GET_GLOBAL_STATUS = 'GET_GLOBAL_STATUS';
export const GET_GLOBAL_DAILY_STATUS = 'GET_GLOBAL_DAILY_STATUS';
export const GET_INFECTED_STATES = 'GET_INFECTED_STATES';
export const GET_STATUS_BY_COUNTRY = 'GET_STATUS_BY_COUNTRY';
